language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "marcocaballero-github"
    token:
      secure: $SONAR_TOKEN
      github-token: $GITHUB_TOKEN
jdk:
  - oraclejdk8
script:
  - sonar-scanner
 # mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'