language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "marcocaballero-github"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - oraclejdk8
before_script:
  - cd testlink-plugin
  - mvn -v
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.sonar/cache'