sudo: true
dist: trusty

services:
  - docker

addons:
  sonarcloud:
    organization: "marcocaballero-github"
    token:
      secure: "$SONAR_TOKEN"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
      
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:

jobs:
  include:
    - stage: Frontend & Backend Unit Testing Phase
      language: java
      jdk: oraclejdk8
      before_script: cd testlink-plugin
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
    - # stage name not required, parallel jobs 
      language: node_js
      node_js: "8.11.1"
      before_script: 
        - cd testlink-plugin-gui
        - npm i -g karma
        - npm i
      script: karma start karma.conf.js --single-run
    - # stage name not required, parallel jobs
      language: node_js
      node_js: "8.11.1"    
      before_script: 
        - cd testlink-plugin-gui
        - npm i
      script: npm run e2e   
    - stage: Build & Release Docker images
      language: python
      python: "2.7"
      before_script: 
        - pip install termcolor
      script:
        - cd docker
        - python build.py --frontend --backend
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
        - chmod u+x deploy_stable.py
        - chmod u+x deploy_version.py
        - if [[ $TRAVIS_COMMIT_MESSAGE == *"[--deploy-DockerHub]"* ]]; 
          then python deploy_stable.py;
          else python deploy_version.py;
          fi;
