sudo: true
dist: trusty

language: java
jdk:
 - oraclejdk8

language: python
python:
  - "2.7"
install:
  - pip install termcolor

services:
  - docker

addons:
  sonarcloud:
    organization: "marcocaballero-github"
    token:
      secure: "$SONAR_TOKEN"

jobs:
  include:
    - stage: backend tests
      script:
        -  cd testlink-plugin
        -  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
    - stage: build & release
      script:
        - cd docker
        - python build.py --frontend --backend
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
        - chmod u+x deploy_stable.py
        - chmod u+x deploy_version.py
        - if [[ $TRAVIS_COMMIT_MESSAGE == *"[--deploy-DockerHub]"* ]]; 
          then python deploy_stable.py;
          else python deploy_version.py;
          fi;
