# language: java
# sudo: false
# install: true
# addons:
#   sonarcloud:
#     organization: "marcocaballero-github"
#     token:
#       secure: "$SONAR_TOKEN"
# jdk:
#   - oraclejdk8
# before_script:
#   - cd testlink-plugin
# script:
#   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -DskipTests sonar:sonar
# cache:
#   directories:
#     - '$HOME/.sonar/cache'

sudo: required
language: java
install: true
jdk:
 - oraclejdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "marcocaballero-github"
    token:
      secure: "$SONAR_TOKEN"

before_script:
  - cd testlink-plugin
  - mvn package -Dmaven.test.skip=true
  - mvn dockerfile:build
  - cd .. 
  - cd testlink-plugin-gui
  - docker build -t marcocab/testlink-plugin-gui .
  - cd ../docker && docker-compose up -d
script:
  - docker exec -it docker_tlp_1 /bin/bash "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
after_script:
  - docker-compose down --volumes --remove-orphans  
cache:
  directories:
    - '$HOME/.sonar/cache'