sudo: required

language: java
jdk:
 - oraclejdk8

language: python
python:
  - "2.7"
install:
  - pip install termcolor

services:
  - docker

addons:
  sonarcloud:
    organization: "marcocaballero-github"
    token:
      secure: "$SONAR_TOKEN"

before_script:
  - cd testlink-plugin
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn dockerfile:build
  - cd .. 
  - cd testlink-plugin-gui
  - docker build -t marcocab/testlink-plugin-gui:dev .
  - cd ..
script:
  - docker-compose up -d
after_success:
  - docker-compose down --volumes --remove-orphans
after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - chmod u+x docker/deploy_stable.py
  - chmod u+x docker/deploy_dev.py
  - cd docker
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"[--deploy-DockerHub]"* ]]; 
    then python docker/deploy_stable.py;
    else python docker/deploy_dev.py;
    fi;
cache:
  directories:
    - '$HOME/.sonar/cache'