sudo: required
language: java
install: true
jdk:
 - oraclejdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "marcocaballero-github"
    token:
      secure: "$SONAR_TOKEN"

before_script:
  - cd testlink-plugin
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn dockerfile:build
  - cd .. 
  - cd testlink-plugin-gui
  - docker build -t marcocab/testlink-plugin-gui .
script:
  - cd ../docker && docker-compose up -d
after_script:
  - docker-compose down --volumes --remove-orphans  
cache:
  directories:
    - '$HOME/.sonar/cache'