@startuml Sequence Diagram - Enrichment
autonumber
actor Tester

participant FilterManager 
participant FilterChain 
participant HttpEnrichmentFilter 
participant RestController 
participant Service 
participant RpcPlugin 
participant TestlinkJavaApi 

Tester -> FilterManager : http
FilterManager -> FilterChain : create
FilterManager -> FilterChain : forward request
FilterChain -> HttpEnrichmentFilter : do filter
HttpEnrichmentFilter -> HttpEnrichmentFilter : get headers
HttpEnrichmentFilter -> RpcPlugin : send data
RpcPlugin -> RpcPlugin : process data
RpcPlugin -> TestlinkJavaApi : create


FilterManager -> RestController : forward request
RestController -> Service : process request
Service -> RpcPlugin : interacts with rpc controllers
RpcPlugin -> TestlinkJavaApi : get server data

alt GET
    TestlinkJavaApi --> RpcPlugin : send data
    RpcPlugin --> Service : send data
    Service --> Service : process data
    Service --> RestController : send data
    RestController -> Tester : Send 200 OK + JSON Body
else POST
    TestlinkJavaApi --> RpcPlugin : ok
    RpcPlugin --> Service : ok
    Service --> RestController : ok
    RestController -> Tester : Send 200 Ok
end

@enduml